// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKdiMNGffSGizVecYgM-w2yW_9d9JD1pY',
    appId: '1:416333615539:web:1548ca397831d2c6073bc6',
    messagingSenderId: '416333615539',
    projectId: 'lugoyogo',
    authDomain: 'lugoyogo.firebaseapp.com',
    storageBucket: 'lugoyogo.firebasestorage.app',
    measurementId: 'G-PRDHLH6REX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqk2v_1qRFbgFb2fHWz16BbwkCNotnmQA',
    appId: '1:416333615539:android:f7a3fb67d2752361073bc6',
    messagingSenderId: '416333615539',
    projectId: 'lugoyogo',
    storageBucket: 'lugoyogo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5YWen9N7v7ByHn_sBToFASTfE1FZEQOU',
    appId: '1:416333615539:ios:5ecfa28576e2656c073bc6',
    messagingSenderId: '416333615539',
    projectId: 'lugoyogo',
    storageBucket: 'lugoyogo.firebasestorage.app',
    iosBundleId: 'com.example.lugoyogo',
  );
}
